site_name: Fried-Tofu-Counting
theme : 
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - search 
    - search.highlight
    - search.sticky
    - toc
    - toc.sticky
    - header.autohide
    - header.sticky
    - navigation.top
nav:
  - Home : index.md
  - Tofu-Counting : 
      - tofu_counting/index.md
      - Introduction : tofu_counting/introduction.md
      - Estimation : tofu_counting/estimation.md
      - Approaches : tofu_counting/approaches.md
      - Dataset Info : tofu_counting/dataset_info.md
